export const ROUTE_PATH = {
  NOT_FOUND: '/404',
  HOME: '/',
  USE_TRUSTLESS: '/use-trustless-computer',
  WALLET: '/wallet',
  CONNECT_WALLET: '/connect-wallet',
  STORE: '/dapp-store',
  PROTOCOL: '/',
  EARN_TC: '/earn-tc',
  DEVELOPER: '/developer',
  DEPLOY: 'https://trustlesside.com/',
  PIONEERS: '/pioneers',
  TOKENS: '/tokens',
  COMPUTER: '/computer',
};
